# This file was generated by the `rails generate rspec:install` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# The generated `.rspec` file contains `--require spec_helper` which will cause
# this file to always be loaded, without a need to explicitly require it in any
# files.
#
# Given that it is always loaded, you are encouraged to keep this file as
# light-weight as possible. Requiring heavyweight dependencies from this file
# will add to the boot time of your test suite on EVERY test run, even for an
# individual file that may not need all of that loaded. Instead, consider making
# a separate helper file that requires the additional dependencies and performs
# the additional setup, and require it from the spec files that actually need
# it.
#
# The `.rspec` file also contains a few flags that are not defaults but that
# users commonly want.
require 'simplecov'
require 'database_cleaner'
require 'codecov'
require 'webmock/rspec'
require 'sidekiq/testing'
require 'pundit/rspec'

Sidekiq::Testing.inline!

SimpleCov.start 'rails' do
  add_group 'Concerns', 'app/models/concerns'
  add_group 'Observers', 'app/observers'
  add_group 'Policies', 'app/policies'
  add_group 'Serializers', 'app/serializers'
end

if ENV['CI']
  SimpleCov.formatters = [
    SimpleCov::Formatter::HTMLFormatter,
    SimpleCov::Formatter::Codecov
  ]

  # save to CircleCI's artifacts directory if we're on CircleCI
  if ENV['CIRCLE_ARTIFACTS']
    dir = File.join(ENV['CIRCLE_ARTIFACTS'], 'coverage')
    SimpleCov.coverage_dir(dir)
  end
end

# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.before :suite do
    DatabaseCleaner[:mongoid].strategy = :truncation
  end

  config.before :each do
    DatabaseCleaner[:mongoid].start
  end

  config.after :each do
    DatabaseCleaner[:mongoid].clean
    Timecop.return
  end
end
